# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20160531_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='listing.Comic'),
        ),
    ]
