# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20160601_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='num',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
