# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20160611_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='issues',
            field=models.ManyToManyField(related_name='creators', to='listing.Issue'),
        ),
    ]
