# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20160601_1424'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='readissue',
            index_together=set([('user', 'issue')]),
        ),
    ]
