# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 05:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_auto_20160611_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readissue',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='readissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
